name: eso
description: 亦搜，亦看，亦闻
publish_to: none
version: 1.22.16+12216
homepage: https://github.com/mabdc/eso
author: mabdc

environment:
#  sdk: ">=2.7.0 <3.2.0"
  sdk: ">=2.18.4 <3.2.0"

dependencies:
  about: ^2.1.1
  archive: ^3.3.5
  audioplayers: ^1.2.0
  battery_plus: ^3.0.2
  cached_network_image: ^3.2.3
  device_info: ^2.0.3

  encrypt: ^5.0.1
  equatable: ^2.0.5
  filesystem_picker: ^3.1.0
  floor: ^1.4.1
  webview_windows: ^0.2.2
#  xpath_selector: ^2.2.4
#  xpath_selector:
#    path: modules/xpath_selector
  xpath_selector: ^3.0.1

  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_localizations:
    sdk: flutter
  flutter_qjs: ^0.3.7
  # text_to_speech: ^0.2.3
  flutter_tts: ^3.6.3

  html: ^0.15.1
  http: ^0.13.5
  image_gallery_saver: ^1.7.1
  intl: ^0.17.0
  json_path: ^0.4.2
  oktoast: ^3.3.1
  package_info_plus: ^1.4.2
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  photo_view: ^0.14.0
  provider: ^6.0.5
  device_display_brightness: ^0.0.6
  share_plus: ^4.5.3
  shared_preferences: ^2.0.15
  sqflite_common_ffi: ^2.2.0+1
  text_composition:
    path: modules/text_composition
  url_launcher: ^6.1.7
  uuid: ^3.0.7
  video_player: ^2.4.10
  # video_player_macos:
  #   git:
  #     url: https://github.com/cbenhagen/plugins.git
  #     path: packages/video_player/video_player_macos
  #     ref: video_player_macos_new
  # video_player_windows:
  #   git:
  #     url: https://github.com/anirudhb/flutter_packages.git
  #     path: video_player_windows

  http_multi_server: ^3.2.1
  window_manager: ^0.2.9
  hive_flutter: ^1.1.0
  explorer: ^2.2.0
  epubx: ^3.0.0
  win32: ^2.6.1
  file_picker: ^4.6.1
  flutter_inappwebview: ^5.7.2+3
  flutter_hooks: ^0.18.5+1

  dlna_dart: ^0.0.4

  webview_flutter: ^4.0.1

  webdav_client: ^1.1.7

#  webdav:
#    # git: https://github.com/timestee/dart-webdav
#    path: modules/dart-webdav
#  webview_flutter:
#    path: modules/webview_flutter
#  flutter_webview:
#    path: modules/flutter_webview
#  dlna:
#    path: modules/DLNA-Dart
#  fast_gbk: ^0.1.2+1
  fast_gbk: ^1.0.0
#  flutter_highlight: ^0.6.0
  flutter_highlight: ^0.7.0
#  matrix_gesture_detector: ^0.1.0
  matrix_gesture_detector: ^0.2.0-nullsafety.1
#  outline_material_icons: ^0.1.1
#  scrollable_positioned_list: ^0.1.10
  scrollable_positioned_list: ^0.3.5


dev_dependencies:
#  build_runner: ^1.11.5
  build_runner: ^2.3.3
  floor_generator: ^1.4.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - player.html
    - CHANGELOG.md
    - README.md
    - LICENSE
    - lib/assets/
    - assets/bg/
    - assets/ba/
    - assets/JsDecoder.js
  fonts:
    - family: fonticons
      fonts:
        - asset: fonts/fonticons.ttf

    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
